services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    c975L\PageEditBundle\Command\:
        resource: '../../Command/*'

    c975L\PageEditBundle\Controller\:
        resource: '../../Controller/*'

    c975L\PageEditBundle\Form\:
        resource: '../../Form/*'

    c975L\PageEditBundle\Security\:
        resource: '../../Security/*'

    c975L\PageEditBundle\Service\:
        resource: '../../Service/*'

    c975L\PageEditBundle\Twig\:
        resource: '../../Twig/*'
