services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    c975L\PageEditBundle\Command\:
        resource: '../src/Command/*'

    c975L\PageEditBundle\Controller\:
        resource: '../src/Controller/*'

    c975L\PageEditBundle\Form\:
        resource: '../src/Form/*'

    c975L\PageEditBundle\Security\:
        resource: '../src/Security/*'

    c975L\PageEditBundle\Service\:
        resource: '../src/Service/*'

    c975L\PageEditBundle\Twig\:
        resource: '../src/Twig/*'
